In [18]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [19]:
data = {
    'Size': ['Small', 'Medium', 'Large', 'Medium', 'Small'],
    'Priority': ['Low', 'High', 'Medium', 'Low', 'High']
}
df = pd.DataFrame(data)
df.head()

     Size Priority
0   Small      Low
1  Medium     High
2   Large   Medium
3  Medium      Low
4   Small     High

In [20]:
le_size = LabelEncoder()
df['size_encoded'] = le_size.fit_transform(df['Size'])
le_priority = LabelEncoder()
df['priority_encoded'] = le_priority.fit_transform(df['Priority'])
df

     Size Priority  size_encoded  priority_encoded
0   Small      Low             2                 1
1  Medium     High             1                 0
2   Large   Medium             0                 2
3  Medium      Low             1                 1
4   Small     High             2                 0

In [21]:
print("Size Mapping: ",dict(zip(le_size.classes_,
                                le_size.transform(le_size.classes_))))
print("Priority Mapping: ",dict(zip(le_priority.classes_,
                                le_priority.transform(le_priority.classes_))))

Size Mapping:  {'Large': np.int64(0), 'Medium': np.int64(1), 'Small': np.int64(2)}
Priority Mapping:  {'High': np.int64(0), 'Low': np.int64(1), 'Medium': np.int64(2)}

In [22]:
decoded_size = le_size.inverse_transform([0,1,2])
print(f"Decoded Size: {decoded_size}")

Decoded Size: ['Large' 'Medium' 'Small']

In [24]:
print(f"\nEncoded DataFrame: ")
print(df)

Encoded DataFrame:
     Size Priority  size_encoded  priority_encoded
0   Small      Low             2                 1
1  Medium     High             1                 0
2   Large   Medium             0                 2
3  Medium      Low             1                 1
4   Small     High             2                 0